### ISSUE TITLE
An issue with piping to request

### ISSUE THREAD

**Issue by finalclass** [npm/node-tar#179]
I'm trying to update `tar` to a recent version however in my particular situation it's not working as expected.
I'm packing some directory and then sending it to couchdb using cradle but for some reason I have a `Write after end` error.

Here is the code that I'm using:

```js
const pathlib = require('path');
const cradle = require('cradle');

const dirToPack = pathlib.join(__dirname, 'some-files');
const CONN_DEFAULTS = {
    cache: false,
    raw: false,
    port: 5984,
    hostname: 'localhost'
};
const connection = new cradle.Connection(CONN_DEFAULTS);
const DB_PACK = 'dbnode-testrepo';
const db = connection.database(DB_PACK);
const tar = require('tar');
const readable = tar.create({
    prefix: dirToPack
}, [dirToPack]);
const writtable = db.saveAttachment({_id: 'test'}, {
    name: 'archive.tar',
    'Content-Type': 'application/x-tar',
}, (err, reply) => {
    if (err) {
        console.error('ERR', err);
    }
    console.log('REPLY', reply);
});
readable.pipe(writtable);
```
to test it you must install `cradle` and `tar` and have a couchdb on your localhost.
The output I see is this:
```
ERR Error: write after end
    at write_ (_http_outgoing.js:625:15)
    at ClientRequest.write (_http_outgoing.js:620:10)
    at Request.write (/home/sel/Documents/spotme/test-tar/node_modules/request/request.js:1501:27)
    at Yallist.pipes.forEach.p (/home/sel/Documents/spotme/test-tar/node_modules/minipass/index.js:263:40)
    at Yallist.forEach (/home/sel/Documents/spotme/test-tar/node_modules/yallist/yallist.js:154:8)
    at Object.emit (/home/sel/Documents/spotme/test-tar/node_modules/minipass/index.js:263:20)
    at Object.write (/home/sel/Documents/spotme/test-tar/node_modules/minipass/index.js:99:17)
    at Object.source.on.chunk (/home/sel/Documents/spotme/test-tar/node_modules/tar/lib/pack.js:344:20)
    at emitOne (events.js:116:13)
    at Object.emit (events.js:211:7)
REPLY undefined
```

Previously we ware using `tar@0.1.19` with `tar.Pack` and it was working just fine. After the update we have this error and saved file is empty. Also if I redirect the stream to a file on a file system it works fine. 
Any advice would be appreciated.

**Comment by isaacs** [comment]
I believe that this was fixed a while back.  Can you try on the latest version?  Istr the issue was emitting `close` before `end`, causing some stream implementations to assume the stream was finished.  (Logically, this still irks me, since `close` is about the underlying resource, not about the stream of data, but we live in the world, not in our ideals.)

**Comment by finalclass** [comment]
I've just tested it again with the recent version of `tar` and the problem is still there.
What I did is simply:
1. copied some files to `./some-files` directory, 
2. then copied the provided script to `a.js`
3. created a database in couchdb: `dbnode-testrepo`
4. run:
```
npm install cradle
npm install tar
```
5. cradle was installed at version 0.7.1 and tar at version 4.4.10
6. run: `node a.js` and the output was:

```
ERR Error: write after end
    at write_ (_http_outgoing.js:622:15)
    at ClientRequest.write (_http_outgoing.js:617:10)
    at Request.write (/home/sel/Documents/spotme/tmp/node_modules/request/request.js:1500:27)
    at Yallist.pipes.forEach.p (/home/sel/Documents/spotme/tmp/node_modules/minipass/index.js:270:40)
    at Yallist.forEach (/home/sel/Documents/spotme/tmp/node_modules/yallist/yallist.js:154:8)
    at Object.emit (/home/sel/Documents/spotme/tmp/node_modules/minipass/index.js:270:20)
    at Object.write (/home/sel/Documents/spotme/tmp/node_modules/minipass/index.js:102:17)
    at Object.source.on.chunk (/home/sel/Documents/spotme/tmp/node_modules/tar/lib/pack.js:345:20)
    at emitOne (events.js:116:13)
    at Object.emit (events.js:211:7)
REPLY undefined
```
So the issue does not seem to be fixed yet.
As a workaround I just store the file on `fs` and then pipe it from there to couch.
